[package]
name = "glob"
version = "0.1.0"
edition = "2021"


[lib]
name = "glob"
crate-type = ["staticlib"]

[dependencies]
glob = "0.3.1"
swift-bridge = "0.1.57"

[build-dependencies]
swift-bridge-build = "0.1"
